import { WorkoutProgram } from '@/types';

export const OPERATION_IRON_14: WorkoutProgram = {
  id: 'operation-iron-14',
  name: '2-WEEK STARTER',
  slug: 'operation-iron-14',
  tagline: '14 days to build the habit — short sessions you can actually finish.',
  subtitle: '14-Day Beginner-Friendly Bodyweight Plan',
  categories: ['fat_burn', 'muscle', 'conditioning', 'discipline', 'calisthenics'],
  durationDays: 14,
  equipment: 'Bodyweight',
  averageWorkout: '20-45 minutes',
  difficulty: 'Beginner to Advanced',
  goals: [
    'Start losing fat gently',
    'Improve energy and cardio',
    'Feel stronger at home',
    'Build a streak you can keep',
    'Stay consistent',
    'Strengthen your core',
  ],
  featured: true,
  militaryThemed: false,
  days: [
    {
      day: 1,
      title: 'FOUNDATION DAY',
      focus: ['Full body', 'Foundation'],
      rounds: 4,
      restSec: { min: 60, max: 90 },
      estimatedMinutes: { min: 20, max: 30 },
      exercises: [
        {
          id: 'd1-pushups',
          name: 'Push-Ups',
          reps: 15,
          recruit: { reps: 10 },
          soldier: { reps: 15 },
          elite: { reps: 20 },
        },
        {
          id: 'd1-squats',
          name: 'Bodyweight Squats',
          reps: 20,
          recruit: { reps: 15 },
          soldier: { reps: 20 },
          elite: { reps: 25 },
        },
        {
          id: 'd1-lunges',
          name: 'Reverse Lunges',
          reps: 10,
          perSide: true,
          recruit: { reps: 8 },
          soldier: { reps: 10 },
          elite: { reps: 12 },
        },
        {
          id: 'd1-climbers',
          name: 'Mountain Climbers',
          reps: 20,
          recruit: { reps: 16 },
          soldier: { reps: 20 },
          elite: { reps: 30 },
        },
        {
          id: 'd1-plank',
          name: 'Plank',
          durationSec: 30,
          recruit: { durationSec: 20 },
          soldier: { durationSec: 30 },
          elite: { durationSec: 45 },
        },
      ],
    },
    {
      day: 2,
      title: 'CARDIO BLAST',
      focus: ['Fat Burn', 'Cardiovascular Conditioning'],
      rounds: 5,
      restSec: { min: 45, max: 75 },
      estimatedMinutes: { min: 22, max: 35 },
      exercises: [
        {
          id: 'd2-burpees',
          name: 'Burpees',
          reps: 10,
          recruit: { reps: 6 },
          soldier: { reps: 10 },
          elite: { reps: 12 },
        },
        {
          id: 'd2-jacks',
          name: 'Jumping Jacks',
          reps: 20,
          recruit: { reps: 15 },
          soldier: { reps: 20 },
          elite: { reps: 30 },
        },
        {
          id: 'd2-squats',
          name: 'Squats',
          reps: 15,
          recruit: { reps: 12 },
          soldier: { reps: 15 },
          elite: { reps: 20 },
        },
        {
          id: 'd2-climbers',
          name: 'Mountain Climbers',
          reps: 20,
          recruit: { reps: 16 },
          soldier: { reps: 20 },
          elite: { reps: 30 },
        },
        {
          id: 'd2-highknees',
          name: 'High Knees',
          durationSec: 30,
          recruit: { durationSec: 20 },
          soldier: { durationSec: 30 },
          elite: { durationSec: 40 },
        },
      ],
    },
    {
      day: 3,
      title: 'UPPER BODY FOCUS',
      focus: ['Chest', 'Shoulders', 'Triceps', 'Core'],
      rounds: 5,
      restSec: { min: 60, max: 90 },
      estimatedMinutes: { min: 25, max: 40 },
      exercises: [
        {
          id: 'd3-pushups',
          name: 'Push-Ups',
          reps: 15,
          recruit: { reps: 10 },
          soldier: { reps: 15 },
          elite: { reps: 20 },
        },
        {
          id: 'd3-diamond',
          name: 'Diamond Push-Ups',
          reps: 10,
          recruit: { reps: 6 },
          soldier: { reps: 10 },
          elite: { reps: 12 },
        },
        {
          id: 'd3-pike',
          name: 'Pike Push-Ups',
          reps: 10,
          recruit: { reps: 6 },
          soldier: { reps: 10 },
          elite: { reps: 12 },
        },
        {
          id: 'd3-dips',
          name: 'Chair Dips',
          reps: '10-15',
          recruit: { reps: 8 },
          soldier: { reps: 12 },
          elite: { reps: 15 },
        },
        {
          id: 'd3-plank',
          name: 'Plank',
          durationSec: 30,
          recruit: { durationSec: 20 },
          soldier: { durationSec: 30 },
          elite: { durationSec: 45 },
        },
      ],
    },
    {
      day: 4,
      title: 'LOWER BODY FOCUS',
      focus: ['Legs', 'Glutes', 'Endurance'],
      rounds: 5,
      restSec: { min: 60, max: 90 },
      estimatedMinutes: { min: 25, max: 35 },
      exercises: [
        {
          id: 'd4-squats',
          name: 'Squats',
          reps: 20,
          recruit: { reps: 15 },
          soldier: { reps: 20 },
          elite: { reps: 25 },
        },
        {
          id: 'd4-lunges',
          name: 'Lunges',
          reps: 12,
          perSide: true,
          recruit: { reps: 8 },
          soldier: { reps: 12 },
          elite: { reps: 15 },
        },
        {
          id: 'd4-bridges',
          name: 'Glute Bridges',
          reps: 15,
          recruit: { reps: 12 },
          soldier: { reps: 15 },
          elite: { reps: 20 },
        },
        {
          id: 'd4-jumpsquats',
          name: 'Jump Squats',
          reps: 10,
          recruit: { reps: 6 },
          soldier: { reps: 10 },
          elite: { reps: 12 },
        },
        {
          id: 'd4-wallsit',
          name: 'Wall Sit',
          durationSec: 30,
          recruit: { durationSec: 20 },
          soldier: { durationSec: 30 },
          elite: { durationSec: 45 },
        },
      ],
    },
    {
      day: 5,
      title: 'FULL-BODY CIRCUIT',
      focus: ['Full body', 'Conditioning'],
      rounds: 5,
      restSec: { min: 45, max: 75 },
      estimatedMinutes: { min: 25, max: 40 },
      exercises: [
        {
          id: 'd5-burpees',
          name: 'Burpees',
          reps: 10,
          recruit: { reps: 6 },
          soldier: { reps: 10 },
          elite: { reps: 12 },
        },
        {
          id: 'd5-pushups',
          name: 'Push-Ups',
          reps: 15,
          recruit: { reps: 10 },
          soldier: { reps: 15 },
          elite: { reps: 20 },
        },
        {
          id: 'd5-squats',
          name: 'Squats',
          reps: 20,
          recruit: { reps: 15 },
          soldier: { reps: 20 },
          elite: { reps: 25 },
        },
        {
          id: 'd5-climbers',
          name: 'Mountain Climbers',
          reps: 20,
          recruit: { reps: 16 },
          soldier: { reps: 20 },
          elite: { reps: 30 },
        },
        {
          id: 'd5-plank',
          name: 'Plank',
          durationSec: 40,
          recruit: { durationSec: 25 },
          soldier: { durationSec: 40 },
          elite: { durationSec: 55 },
        },
      ],
    },
    {
      day: 6,
      title: 'ENDURANCE PACE',
      focus: ['Cardio', 'Endurance'],
      rounds: 3,
      restSec: { min: 45, max: 60 },
      estimatedMinutes: { min: 35, max: 55 },
      exercises: [
        {
          id: 'd6-squats',
          name: 'Squats',
          reps: 20,
          recruit: { reps: 15 },
          soldier: { reps: 20 },
          elite: { reps: 25 },
        },
        {
          id: 'd6-pushups',
          name: 'Push-Ups',
          reps: 10,
          recruit: { reps: 8 },
          soldier: { reps: 10 },
          elite: { reps: 15 },
        },
        {
          id: 'd6-plank',
          name: 'Plank',
          durationSec: 30,
          recruit: { durationSec: 20 },
          soldier: { durationSec: 30 },
          elite: { durationSec: 45 },
        },
      ],
      extraBlocks: [
        {
          title: 'Endurance March',
          description: '30-45 minute brisk walk or jog before the circuit.',
        },
      ],
    },
    {
      day: 7,
      title: 'ACTIVE RECOVERY',
      focus: ['Recovery', 'Mobility'],
      isRecovery: true,
      estimatedMinutes: { min: 40, max: 60 },
      exercises: [],
      coachMessage:
        "Recovery is part of training. Your mission today isn't intensity. It's preparing your body for Week 2.",
      extraBlocks: [
        { title: 'Walk', description: '30-45 minute easy walk.' },
        {
          title: 'Mobility',
          description: '10-15 minutes of mobility and stretching.',
        },
      ],
    },
    {
      day: 8,
      title: 'PROGRESSION',
      focus: ['Full body', 'Volume'],
      rounds: 5,
      restSec: { min: 45, max: 75 },
      estimatedMinutes: { min: 25, max: 40 },
      exercises: [
        {
          id: 'd8-pushups',
          name: 'Push-Ups',
          reps: 20,
          recruit: { reps: 12 },
          soldier: { reps: 20 },
          elite: { reps: 25 },
        },
        {
          id: 'd8-squats',
          name: 'Squats',
          reps: 25,
          recruit: { reps: 18 },
          soldier: { reps: 25 },
          elite: { reps: 30 },
        },
        {
          id: 'd8-lunges',
          name: 'Lunges',
          reps: 12,
          perSide: true,
          recruit: { reps: 8 },
          soldier: { reps: 12 },
          elite: { reps: 15 },
        },
        {
          id: 'd8-climbers',
          name: 'Mountain Climbers',
          reps: 30,
          recruit: { reps: 20 },
          soldier: { reps: 30 },
          elite: { reps: 40 },
        },
        {
          id: 'd8-plank',
          name: 'Plank',
          durationSec: 45,
          recruit: { durationSec: 30 },
          soldier: { durationSec: 45 },
          elite: { durationSec: 60 },
        },
      ],
    },
    {
      day: 9,
      title: 'CONDITIONING DAY',
      focus: ['Conditioning', 'Fat Burn'],
      rounds: 6,
      restSec: { min: 30, max: 60 },
      estimatedMinutes: { min: 25, max: 40 },
      exercises: [
        {
          id: 'd9-burpees',
          name: 'Burpees',
          reps: 8,
          recruit: { reps: 5 },
          soldier: { reps: 8 },
          elite: { reps: 10 },
        },
        {
          id: 'd9-pushups',
          name: 'Push-Ups',
          reps: 15,
          recruit: { reps: 10 },
          soldier: { reps: 15 },
          elite: { reps: 20 },
        },
        {
          id: 'd9-lunges',
          name: 'Alternating Lunges',
          reps: 20,
          recruit: { reps: 14 },
          soldier: { reps: 20 },
          elite: { reps: 24 },
        },
        {
          id: 'd9-highknees',
          name: 'High Knees',
          durationSec: 30,
          recruit: { durationSec: 20 },
          soldier: { durationSec: 30 },
          elite: { durationSec: 40 },
        },
      ],
    },
    {
      day: 10,
      title: 'UPPER BODY FOCUS II',
      focus: ['Chest', 'Shoulders', 'Triceps', 'Core'],
      rounds: 5,
      restSec: { min: 60, max: 90 },
      estimatedMinutes: { min: 25, max: 40 },
      exercises: [
        {
          id: 'd10-pushups',
          name: 'Push-Ups',
          reps: 20,
          recruit: { reps: 12 },
          soldier: { reps: 20 },
          elite: { reps: 25 },
        },
        {
          id: 'd10-diamond',
          name: 'Diamond Push-Ups',
          reps: 12,
          recruit: { reps: 8 },
          soldier: { reps: 12 },
          elite: { reps: 15 },
        },
        {
          id: 'd10-pike',
          name: 'Pike Push-Ups',
          reps: 12,
          recruit: { reps: 8 },
          soldier: { reps: 12 },
          elite: { reps: 15 },
        },
        {
          id: 'd10-dips',
          name: 'Chair Dips',
          reps: 15,
          recruit: { reps: 10 },
          soldier: { reps: 15 },
          elite: { reps: 18 },
        },
        {
          id: 'd10-plank',
          name: 'Plank',
          durationSec: 45,
          recruit: { durationSec: 30 },
          soldier: { durationSec: 45 },
          elite: { durationSec: 60 },
        },
      ],
    },
    {
      day: 11,
      title: 'LEG ASSAULT',
      focus: ['Legs', 'Glutes'],
      rounds: 5,
      restSec: { min: 60, max: 90 },
      estimatedMinutes: { min: 25, max: 40 },
      exercises: [
        {
          id: 'd11-squats',
          name: 'Squats',
          reps: 30,
          recruit: { reps: 20 },
          soldier: { reps: 30 },
          elite: { reps: 35 },
        },
        {
          id: 'd11-lunges',
          name: 'Lunges',
          reps: 15,
          perSide: true,
          recruit: { reps: 10 },
          soldier: { reps: 15 },
          elite: { reps: 18 },
        },
        {
          id: 'd11-bridges',
          name: 'Glute Bridges',
          reps: 20,
          recruit: { reps: 15 },
          soldier: { reps: 20 },
          elite: { reps: 25 },
        },
        {
          id: 'd11-jumpsquats',
          name: 'Jump Squats',
          reps: 12,
          recruit: { reps: 8 },
          soldier: { reps: 12 },
          elite: { reps: 15 },
        },
        {
          id: 'd11-wallsit',
          name: 'Wall Sit',
          durationSec: 45,
          recruit: { durationSec: 30 },
          soldier: { durationSec: 45 },
          elite: { durationSec: 60 },
        },
      ],
    },
    {
      day: 12,
      title: 'FAT-BURN GAUNTLET',
      focus: ['Fat Burn', 'Conditioning'],
      rounds: 6,
      restSec: { min: 30, max: 60 },
      estimatedMinutes: { min: 25, max: 40 },
      exercises: [
        {
          id: 'd12-burpees',
          name: 'Burpees',
          reps: 10,
          recruit: { reps: 6 },
          soldier: { reps: 10 },
          elite: { reps: 12 },
        },
        {
          id: 'd12-climbers',
          name: 'Mountain Climbers',
          reps: 20,
          recruit: { reps: 16 },
          soldier: { reps: 20 },
          elite: { reps: 30 },
        },
        {
          id: 'd12-pushups',
          name: 'Push-Ups',
          reps: 15,
          recruit: { reps: 10 },
          soldier: { reps: 15 },
          elite: { reps: 20 },
        },
        {
          id: 'd12-squats',
          name: 'Squats',
          reps: 20,
          recruit: { reps: 15 },
          soldier: { reps: 20 },
          elite: { reps: 25 },
        },
        {
          id: 'd12-highknees',
          name: 'High Knees',
          durationSec: 30,
          recruit: { durationSec: 20 },
          soldier: { durationSec: 30 },
          elite: { durationSec: 40 },
        },
      ],
    },
    {
      day: 13,
      title: 'FINAL PREPARATION',
      focus: ['Controlled volume', 'Recovery prep'],
      rounds: 4,
      restSec: { min: 60, max: 90 },
      estimatedMinutes: { min: 40, max: 55 },
      exercises: [
        {
          id: 'd13-pushups',
          name: 'Push-Ups',
          reps: 15,
          recruit: { reps: 10 },
          soldier: { reps: 15 },
          elite: { reps: 18 },
        },
        {
          id: 'd13-squats',
          name: 'Squats',
          reps: 20,
          recruit: { reps: 15 },
          soldier: { reps: 20 },
          elite: { reps: 25 },
        },
        {
          id: 'd13-lunges',
          name: 'Lunges',
          reps: 10,
          perSide: true,
          recruit: { reps: 8 },
          soldier: { reps: 10 },
          elite: { reps: 12 },
        },
        {
          id: 'd13-plank',
          name: 'Plank',
          durationSec: 30,
          recruit: { durationSec: 20 },
          soldier: { durationSec: 30 },
          elite: { durationSec: 40 },
        },
      ],
      extraBlocks: [
        {
          title: 'Walk',
          description: 'Complete a 30-minute walk after the controlled rounds.',
        },
      ],
    },
    {
      day: 14,
      title: 'FINAL TEST',
      focus: ['Max effort', 'Challenge completion'],
      isFinalTest: true,
      estimatedMinutes: { min: 40, max: 70 },
      exercises: [
        {
          id: 'd14-pushups',
          name: 'Push-Ups',
          reps: 100,
          notes: 'Divide into manageable sets.',
          recruit: { reps: 60 },
          soldier: { reps: 100 },
          elite: { reps: 120 },
        },
        {
          id: 'd14-squats',
          name: 'Squats',
          reps: 150,
          notes: 'Divide into manageable sets.',
          recruit: { reps: 100 },
          soldier: { reps: 150 },
          elite: { reps: 180 },
        },
        {
          id: 'd14-lunges',
          name: 'Alternating Lunges',
          reps: 100,
          notes: 'Divide into manageable sets.',
          recruit: { reps: 60 },
          soldier: { reps: 100 },
          elite: { reps: 120 },
        },
        {
          id: 'd14-climbers',
          name: 'Mountain Climbers',
          reps: 100,
          notes: 'Divide into manageable sets.',
          recruit: { reps: 60 },
          soldier: { reps: 100 },
          elite: { reps: 120 },
        },
        {
          id: 'd14-burpees',
          name: 'Burpees',
          reps: 50,
          notes: 'Divide into manageable sets.',
          recruit: { reps: 30 },
          soldier: { reps: 50 },
          elite: { reps: 60 },
        },
        {
          id: 'd14-plank',
          name: 'Planks (total)',
          durationSec: 300,
          notes: '5 total minutes across sets.',
          recruit: { durationSec: 180 },
          soldier: { durationSec: 300 },
          elite: { durationSec: 360 },
        },
      ],
      coachMessage: 'Finish strong. Pace yourself. Complete every rep.',
    },
  ],
};
